# Generated by Django 4.1.2 on 2022-11-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=100)),
                ("restaurant_link", models.CharField(max_length=500)),
                ("restaurant_content", models.TextField()),
                ("restaurant_keyword", models.CharField(max_length=50)),
            ],
        ),
    ]
