# Generated by Django 4.1.2 on 2022-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CateWeights",
            fields=[
                (
                    "dong_code",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("dong", models.CharField(blank=True, max_length=30, null=True)),
                ("gu", models.CharField(blank=True, max_length=30, null=True)),
                ("car_shr_num", models.FloatField(blank=True, null=True)),
                ("ani_hspt_num", models.FloatField(blank=True, null=True)),
                ("leisure_num", models.FloatField(blank=True, null=True)),
                ("gym_num", models.FloatField(blank=True, null=True)),
                ("golf_num", models.FloatField(blank=True, null=True)),
                ("starbucks_num", models.FloatField(blank=True, null=True)),
                ("mc_num", models.FloatField(blank=True, null=True)),
                ("vegan_cnt", models.FloatField(blank=True, null=True)),
                ("safe_dlvr_num", models.FloatField(blank=True, null=True)),
                ("kids_num", models.FloatField(blank=True, null=True)),
                ("noise_vibration_num", models.FloatField(blank=True, null=True)),
                ("park_num", models.FloatField(blank=True, null=True)),
                ("coliving_num", models.FloatField(blank=True, null=True)),
                ("mz_pop_cnt", models.FloatField(blank=True, null=True)),
                ("transportation", models.FloatField(blank=True, null=True)),
                ("education", models.FloatField(blank=True, null=True)),
                ("parenting", models.FloatField(blank=True, null=True)),
                ("safety", models.FloatField(blank=True, null=True)),
                ("medical", models.FloatField(blank=True, null=True)),
                ("facilities", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "cate_weights",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DongCnt",
            fields=[
                (
                    "dong_code",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("dong", models.CharField(blank=True, max_length=30, null=True)),
                ("gu", models.CharField(blank=True, max_length=30, null=True)),
                ("car_shr_num", models.FloatField(blank=True, null=True)),
                ("ani_hspt_num", models.FloatField(blank=True, null=True)),
                ("leisure_num", models.FloatField(blank=True, null=True)),
                ("gym_num", models.FloatField(blank=True, null=True)),
                ("golf_num", models.FloatField(blank=True, null=True)),
                ("starbucks_num", models.FloatField(blank=True, null=True)),
                ("mc_num", models.FloatField(blank=True, null=True)),
                ("vegan_cnt", models.FloatField(blank=True, null=True)),
                ("safe_dlvr_num", models.FloatField(blank=True, null=True)),
                ("kids_num", models.FloatField(blank=True, null=True)),
                ("noise_vibration_num", models.FloatField(blank=True, null=True)),
                ("park_num", models.FloatField(blank=True, null=True)),
                ("coliving_num", models.FloatField(blank=True, null=True)),
                ("mz_pop_cnt", models.FloatField(blank=True, null=True)),
                ("transportation", models.FloatField(blank=True, null=True)),
                ("education", models.FloatField(blank=True, null=True)),
                ("parenting", models.FloatField(blank=True, null=True)),
                ("safety", models.FloatField(blank=True, null=True)),
                ("medical", models.FloatField(blank=True, null=True)),
                ("facilities", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "dong_cnt",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
